name: api

on:
  push:
    paths:
      - 'apps/api/**'
      - '.github/workflows/api.yml'

jobs:
  typecheck:
    runs-on: [self-hosted, pm-runner]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - run: |
          cd apps/api
          npm ci
          npm run tsc
    env:
      CI: true

  lint:
    runs-on: [self-hosted, pm-runner]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Lint Dockerfile
        run: docker run --rm -i hadolint/hadolint < ./apps/api/Dockerfile

      - run: |
          cd apps/api
          npm ci
          npm run lint
    env:
      CI: true

  test:
    runs-on: [self-hosted, pm-runner]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - run: |
          cd apps/api
          npm ci
          npm run coverage
    env:
      CI: true

  build:
    needs: [typecheck, lint, test]
    if: github.ref == 'refs/heads/master' || contains(github.ref, 'refs/tags/')
    runs-on: [self-hosted, pm-runner]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Log into registry
        run: echo "$CI_REGISTRY_PASSWORD" | docker login registry.aldisameriks.dev -u $CI_REGISTRY_USER --password-stdin

      - run: |
          cd apps/api
          npm run docker:build

      - name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'registry.aldisameriks.dev/pm-api'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL'

      - name: Tag image
        if: contains(github.ref, 'refs/tags/')
        run: |
          docker tag registry.aldisameriks.dev/pm-api:latest registry.aldisameriks.dev/pm-api:${GITHUB_REF#refs/tags/}
          docker push registry.aldisameriks.dev/pm-api:${GITHUB_REF#refs/tags/}

      - name: Push latest
        if: github.ref == 'refs/heads/master'
        run: |
          cd apps/api
          npm run docker:push

    env:
      CI: true
